# Build stage
FROM golang:1.22-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod/
RUN go mod download -x

COPY . .
RUN --mount=type=cache,target=/go/pkg/mod/ go build -o api_service main.go

# Final stage
FROM alpine:latest  

WORKDIR /app

COPY --from=builder /app/api_service .
COPY .env .env

EXPOSE 8080

CMD [ "./api_service" ]
