# Build stage
FROM golang:1.22-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .
RUN go build -o consumer_service ./consumer/main.go

# Final stage
FROM alpine:latest  

WORKDIR /app

COPY --from=builder /app/consumer_service .
COPY .env .env

CMD [ "./consumer_service" ]
